on:
  push:
    branches:
      - main

name: test

jobs:
  sanity-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Prepare environment
        run: |
          python -m pip install --upgrade pip
          python -m pip install wheel
          python -m pip install docarray[common]
          python -m pip install jina
      - name: Run checks
        run: |
          python ./sanity-checks/check-docarray.py
          python ./sanity-checks/check-executor-pull.py
          python ./sanity-checks/check-artifact.py
          python ./sanity-checks/check-user-api.py