on:
  push:
    branches:
      - main

name: test

jobs:
  sanity-check:
    runs-on: ubuntu-latest

    env:
      JINA_AUTH_TOKEN: ${{ secrets.JINA_AUTH_TOKEN}}

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Prepare environment
        run: |
          python -m pip install --upgrade pip
          python -m pip install wheel
          python -m pip install docarray[common]
          python -m pip install jina
      - name: Run checks
        env:
          JINA_HUBBLE_REGISTRY: https://apihubble.staging.jina.ai
        run: |
          python ./sanity-checks/check-executor-pull.py